In [25]:
import requests
import pandas as pd

**Работа с API**

1. Получить информацию обо всех книгах и сохранить в pd.DataFrame

In [26]:
all_books = requests.get('https://www.anapioficeandfire.com/api/books')
print(all_books.json())

[{'url': 'https://www.anapioficeandfire.com/api/books/1', 'name': 'A Game of Thrones', 'isbn': '978-0553103540', 'authors': ['George R. R. Martin'], 'numberOfPages': 694, 'publisher': 'Bantam Books', 'country': 'United States', 'mediaType': 'Hardcover', 'released': '1996-08-01T00:00:00', 'characters': ['https://www.anapioficeandfire.com/api/characters/2', 'https://www.anapioficeandfire.com/api/characters/12', 'https://www.anapioficeandfire.com/api/characters/13', 'https://www.anapioficeandfire.com/api/characters/16', 'https://www.anapioficeandfire.com/api/characters/20', 'https://www.anapioficeandfire.com/api/characters/27', 'https://www.anapioficeandfire.com/api/characters/31', 'https://www.anapioficeandfire.com/api/characters/38', 'https://www.anapioficeandfire.com/api/characters/39', 'https://www.anapioficeandfire.com/api/characters/40', 'https://www.anapioficeandfire.com/api/characters/41', 'https://www.anapioficeandfire.com/api/characters/42', 'https://www.anapioficeandfire.com/api/characters/46', 'https://www.anapioficeandfire.com/api/characters/54', 'https://www.anapioficeandfire.com/api/characters/56', 'https://www.anapioficeandfire.com/api/characters/57', 'https://www.anapioficeandfire.com/api/characters/60', 'https://www.anapioficeandfire.com/api/characters/61', 'https://www.anapioficeandfire.com/api/characters/62', 'https://www.anapioficeandfire.com/api/characters/66', 'https://www.anapioficeandfire.com/api/characters/67', 'https://www.anapioficeandfire.com/api/characters/69', 'https://www.anapioficeandfire.com/api/characters/79', 'https://www.anapioficeandfire.com/api/characters/89', 'https://www.anapioficeandfire.com/api/characters/107', 'https://www.anapioficeandfire.com/api/characters/115', 'https://www.anapioficeandfire.com/api/characters/116', 'https://www.anapioficeandfire.com/api/characters/120', 'https://www.anapioficeandfire.com/api/characters/125', 'https://www.anapioficeandfire.com/api/characters/128', 'https://www.anapioficeandfire.com/api/characters/129', 'https://www.anapioficeandfire.com/api/characters/130', 'https://www.anapioficeandfire.com/api/characters/135', 'https://www.anapioficeandfire.com/api/characters/137', 'https://www.anapioficeandfire.com/api/characters/142', 'https://www.anapioficeandfire.com/api/characters/147', 'https://www.anapioficeandfire.com/api/characters/149', 'https://www.anapioficeandfire.com/api/characters/150', 'https://www.anapioficeandfire.com/api/characters/151', 'https://www.anapioficeandfire.com/api/characters/160', 'https://www.anapioficeandfire.com/api/characters/164', 'https://www.anapioficeandfire.com/api/characters/168', 'https://www.anapioficeandfire.com/api/characters/171', 'https://www.anapioficeandfire.com/api/characters/181', 'https://www.anapioficeandfire.com/api/characters/190', 'https://www.anapioficeandfire.com/api/characters/194', 'https://www.anapioficeandfire.com/api/characters/198', 'https://www.anapioficeandfire.com/api/characters/202', 'https://www.anapioficeandfire.com/api/characters/203', 'https://www.anapioficeandfire.com/api/characters/206', 'https://www.anapioficeandfire.com/api/characters/209', 'https://www.anapioficeandfire.com/api/characters/211', 'https://www.anapioficeandfire.com/api/characters/213', 'https://www.anapioficeandfire.com/api/characters/217', 'https://www.anapioficeandfire.com/api/characters/220', 'https://www.anapioficeandfire.com/api/characters/223', 'https://www.anapioficeandfire.com/api/characters/225', 'https://www.anapioficeandfire.com/api/characters/235', 'https://www.anapioficeandfire.com/api/characters/238', 'https://www.anapioficeandfire.com/api/characters/245', 'https://www.anapioficeandfire.com/api/characters/259', 'https://www.anapioficeandfire.com/api/characters/264', 'https://www.anapioficeandfire.com/api/characters/273', 'https://www.anapioficeandfire.com/api/characters/274', 'https://www.anapioficeandfire.com/api/characters/291', 'https://www.anapioficeandfire.com/api/characters/292', 'https://www.anapioficeandfire.com/api/characters/293', 'https://www.anapioficeandfire.com/api/characters/294', 'https://www.anapioficeandfire.com/api/characters/303', 'https://www.anapioficeandfire.com/api/characters/306', 'https://www.anapioficeandfire.com/api/characters/313', 'https://www.anapioficeandfire.com/api/characters/315', 'https://www.anapioficeandfire.com/api/characters/325', 'https://www.anapioficeandfire.com/api/characters/326', 'https://www.anapioficeandfire.com/api/characters/327', 'https://www.anapioficeandfire.com/api/characters/338', 'https://www.anapioficeandfire.com/api/characters/346', 'https://www.anapioficeandfire.com/api/characters/347', 'https://www.anapioficeandfire.com/api/characters/348', 'https://www.anapioficeandfire.com/api/characters/361', 'https://www.anapioficeandfire.com/api/characters/368', 'https://www.anapioficeandfire.com/api/characters/377', 'https://www.anapioficeandfire.com/api/characters/379', 'https://www.anapioficeandfire.com/api/characters/380', 'https://www.anapioficeandfire.com/api/characters/384', 'https://www.anapioficeandfire.com/api/characters/385', 'https://www.anapioficeandfire.com/api/characters/393', 'https://www.anapioficeandfire.com/api/characters/394', 'https://www.anapioficeandfire.com/api/characters/397', 'https://www.anapioficeandfire.com/api/characters/400', 'https://www.anapioficeandfire.com/api/characters/401', 'https://www.anapioficeandfire.com/api/characters/405', 'https://www.anapioficeandfire.com/api/characters/408', 'https://www.anapioficeandfire.com/api/characters/413', 'https://www.anapioficeandfire.com/api/characters/415', 'https://www.anapioficeandfire.com/api/characters/418', 'https://www.anapioficeandfire.com/api/characters/421', 'https://www.anapioficeandfire.com/api/characters/427', 'https://www.anapioficeandfire.com/api/characters/435', 'https://www.anapioficeandfire.com/api/characters/439', 'https://www.anapioficeandfire.com/api/characters/458', 'https://www.anapioficeandfire.com/api/characters/461', 'https://www.anapioficeandfire.com/api/characters/463', 'https://www.anapioficeandfire.com/api/characters/466', 'https://www.anapioficeandfire.com/api/characters/467', 'https://www.anapioficeandfire.com/api/characters/475', 'https://www.anapioficeandfire.com/api/characters/476', 'https://www.anapioficeandfire.com/api/characters/484', 'https://www.anapioficeandfire.com/api/characters/487', 'https://www.anapioficeandfire.com/api/characters/490', 'https://www.anapioficeandfire.com/api/characters/494', 'https://www.anapioficeandfire.com/api/characters/496', 'https://www.anapioficeandfire.com/api/characters/498', 'https://www.anapioficeandfire.com/api/characters/501', 'https://www.anapioficeandfire.com/api/characters/503', 'https://www.anapioficeandfire.com/api/characters/506', 'https://www.anapioficeandfire.com/api/characters/508', 'https://www.anapioficeandfire.com/api/characters/519', 'https://www.anapioficeandfire.com/api/characters/521', 'https://www.anapioficeandfire.com/api/characters/526', 'https://www.anapioficeandfire.com/api/characters/527', 'https://www.anapioficeandfire.com/api/characters/529', 'https://www.anapioficeandfire.com/api/characters/531', 'https://www.anapioficeandfire.com/api/characters/532', 'https://www.anapioficeandfire.com/api/characters/533', 'https://www.anapioficeandfire.com/api/characters/535', 'https://www.anapioficeandfire.com/api/characters/536', 'https://www.anapioficeandfire.com/api/characters/539', 'https://www.anapioficeandfire.com/api/characters/547', 'https://www.anapioficeandfire.com/api/characters/557', 'https://www.anapioficeandfire.com/api/characters/558', 'https://www.anapioficeandfire.com/api/characters/562', 'https://www.anapioficeandfire.com/api/characters/565', 'https://www.anapioficeandfire.com/api/characters/572', 'https://www.anapioficeandfire.com/api/characters/584', 'https://www.anapioficeandfire.com/api/characters/585', 'https://www.anapioficeandfire.com/api/characters/586', 'https://www.anapioficeandfire.com/api/characters/588', 'https://www.anapioficeandfire.com/api/characters/595', 'https://www.anapioficeandfire.com/api/characters/600', 'https://www.anapioficeandfire.com/api/characters/604', 'https://www.anapioficeandfire.com/api/characters/605', 'https://www.anapioficeandfire.com/api/characters/613', 'https://www.anapioficeandfire.com/api/characters/615', 'https://www.anapioficeandfire.com/api/characters/622', 'https://www.anapioficeandfire.com/api/characters/631', 'https://www.anapioficeandfire.com/api/characters/632', 'https://www.anapioficeandfire.com/api/characters/635', 'https://www.anapioficeandfire.com/api/characters/640', 'https://www.anapioficeandfire.com/api/characters/649', 'https://www.anapioficeandfire.com/api/characters/650', 'https://www.anapioficeandfire.com/api/characters/651', 'https://www.anapioficeandfire.com/api/characters/672', 'https://www.anapioficeandfire.com/api/characters/677', 'https://www.anapioficeandfire.com/api/characters/688', 'https://www.anapioficeandfire.com/api/characters/691', 'https://www.anapioficeandfire.com/api/characters/692', 'https://www.anapioficeandfire.com/api/characters/694', 'https://www.anapioficeandfire.com/api/characters/695', 'https://www.anapioficeandfire.com/api/characters/701', 'https://www.anapioficeandfire.com/api/characters/709', 'https://www.anapioficeandfire.com/api/characters/714', 'https://www.anapioficeandfire.com/api/characters/718', 'https://www.anapioficeandfire.com/api/characters/721', 'https://www.anapioficeandfire.com/api/characters/724', 'https://www.anapioficeandfire.com/api/characters/725', 'https://www.anapioficeandfire.com/api/characters/731', 'https://www.anapioficeandfire.com/api/characters/734', 'https://www.anapioficeandfire.com/api/characters/749', 'https://www.anapioficeandfire.com/api/characters/751', 'https://www.anapioficeandfire.com/api/characters/752', 'https://www.anapioficeandfire.com/api/characters/754', 'https://www.anapioficeandfire.com/api/characters/755', 'https://www.anapioficeandfire.com/api/characters/759', 'https://www.anapioficeandfire.com/api/characters/766', 'https://www.anapioficeandfire.com/api/characters/768', 'https://www.anapioficeandfire.com/api/characters/775', 'https://www.anapioficeandfire.com/api/characters/778', 'https://www.anapioficeandfire.com/api/characters/779', 'https://www.anapioficeandfire.com/api/characters/782', 'https://www.anapioficeandfire.com/api/characters/784', 'https://www.anapioficeandfire.com/api/characters/786', 'https://www.anapioficeandfire.com/api/characters/797', 'https://www.anapioficeandfire.com/api/characters/805', 'https://www.anapioficeandfire.com/api/characters/806', 'https://www.anapioficeandfire.com/api/characters/814', 'https://www.anapioficeandfire.com/api/characters/815', 'https://www.anapioficeandfire.com/api/characters/820', 'https://www.anapioficeandfire.com/api/characters/823', 'https://www.anapioficeandfire.com/api/characters/827', 'https://www.anapioficeandfire.com/api/characters/828', 'https://www.anapioficeandfire.com/api/characters/829', 'https://www.anapioficeandfire.com/api/characters/832', 'https://www.anapioficeandfire.com/api/characters/837', 'https://www.anapioficeandfire.com/api/characters/844', 'https://www.anapioficeandfire.com/api/characters/850', 'https://www.anapioficeandfire.com/api/characters/852', 'https://www.anapioficeandfire.com/api/characters/860', 'https://www.anapioficeandfire.com/api/characters/862', 'https://www.anapioficeandfire.com/api/characters/867', 'https://www.anapioficeandfire.com/api/characters/869', 'https://www.anapioficeandfire.com/api/characters/876', 'https://www.anapioficeandfire.com/api/characters/884', 'https://www.anapioficeandfire.com/api/characters/886', 'https://www.anapioficeandfire.com/api/characters/887', 'https://www.anapioficeandfire.com/api/characters/891', 'https://www.anapioficeandfire.com/api/characters/892', 'https://www.anapioficeandfire.com/api/characters/894', 'https://www.anapioficeandfire.com/api/characters/901', 'https://www.anapioficeandfire.com/api/characters/903', 'https://www.anapioficeandfire.com/api/characters/909', 'https://www.anapioficeandfire.com/api/characters/912', 'https://www.anapioficeandfire.com/api/characters/913', 'https://www.anapioficeandfire.com/api/characters/916', 'https://www.anapioficeandfire.com/api/characters/933', 'https://www.anapioficeandfire.com/api/characters/945', 'https://www.anapioficeandfire.com/api/characters/954', 'https://www.anapioficeandfire.com/api/characters/955', 'https://www.anapioficeandfire.com/api/characters/969', 'https://www.anapioficeandfire.com/api/characters/972', 'https://www.anapioficeandfire.com/api/characters/975', 'https://www.anapioficeandfire.com/api/characters/983', 'https://www.anapioficeandfire.com/api/characters/984', 'https://www.anapioficeandfire.com/api/characters/994', 'https://www.anapioficeandfire.com/api/characters/1010', 'https://www.anapioficeandfire.com/api/characters/1017', 'https://www.anapioficeandfire.com/api/characters/1022', 'https://www.anapioficeandfire.com/api/characters/1023', 'https://www.anapioficeandfire.com/api/characters/1025', 'https://www.anapioficeandfire.com/api/characters/1029', 'https://www.anapioficeandfire.com/api/characters/1033', 'https://www.anapioficeandfire.com/api/characters/1034', 'https://www.anapioficeandfire.com/api/characters/1043', 'https://www.anapioficeandfire.com/api/characters/1044', 'https://www.anapioficeandfire.com/api/characters/1049', 'https://www.anapioficeandfire.com/api/characters/1051', 'https://www.anapioficeandfire.com/api/characters/1055', 'https://www.anapioficeandfire.com/api/characters/1063', 'https://www.anapioficeandfire.com/api/characters/1068', 'https://www.anapioficeandfire.com/api/characters/1069', 'https://www.anapioficeandfire.com/api/characters/1072', 'https://www.anapioficeandfire.com/api/characters/1074', 'https://www.anapioficeandfire.com/api/characters/1076', 'https://www.anapioficeandfire.com/api/characters/1077', 'https://www.anapioficeandfire.com/api/characters/1079', 'https://www.anapioficeandfire.com/api/characters/1080', 'https://www.anapioficeandfire.com/api/characters/1089', 'https://www.anapioficeandfire.com/api/characters/1090', 'https://www.anapioficeandfire.com/api/characters/1091', 'https://www.anapioficeandfire.com/api/characters/1093', 'https://www.anapioficeandfire.com/api/characters/1096', 'https://www.anapioficeandfire.com/api/characters/1104', 'https://www.anapioficeandfire.com/api/characters/1106', 'https://www.anapioficeandfire.com/api/characters/1107', 'https://www.anapioficeandfire.com/api/characters/1110', 'https://www.anapioficeandfire.com/api/characters/1113', 'https://www.anapioficeandfire.com/api/characters/1114', 'https://www.anapioficeandfire.com/api/characters/1116', 'https://www.anapioficeandfire.com/api/characters/1120', 'https://www.anapioficeandfire.com/api/characters/1122', 'https://www.anapioficeandfire.com/api/characters/1124', 'https://www.anapioficeandfire.com/api/characters/1131', 'https://www.anapioficeandfire.com/api/characters/1132', 'https://www.anapioficeandfire.com/api/characters/1140', 'https://www.anapioficeandfire.com/api/characters/1142', 'https://www.anapioficeandfire.com/api/characters/1147', 'https://www.anapioficeandfire.com/api/characters/1152', 'https://www.anapioficeandfire.com/api/characters/1158', 'https://www.anapioficeandfire.com/api/characters/1165', 'https://www.anapioficeandfire.com/api/characters/1166', 'https://www.anapioficeandfire.com/api/characters/1178', 'https://www.anapioficeandfire.com/api/characters/1188', 'https://www.anapioficeandfire.com/api/characters/1193', 'https://www.anapioficeandfire.com/api/characters/1214', 'https://www.anapioficeandfire.com/api/characters/1219', 'https://www.anapioficeandfire.com/api/characters/1228', 'https://www.anapioficeandfire.com/api/characters/1245', 'https://www.anapioficeandfire.com/api/characters/1247', 'https://www.anapioficeandfire.com/api/characters/1253', 'https://www.anapioficeandfire.com/api/characters/1260', 'https://www.anapioficeandfire.com/api/characters/1262', 'https://www.anapioficeandfire.com/api/characters/1265', 'https://www.anapioficeandfire.com/api/characters/1266', 'https://www.anapioficeandfire.com/api/characters/1267', 'https://www.anapioficeandfire.com/api/characters/1268', 'https://www.anapioficeandfire.com/api/characters/1269', 'https://www.anapioficeandfire.com/api/characters/1275', 'https://www.anapioficeandfire.com/api/characters/1277', 'https://www.anapioficeandfire.com/api/characters/1278', 'https://www.anapioficeandfire.com/api/characters/1280', 'https://www.anapioficeandfire.com/api/characters/1282', 'https://www.anapioficeandfire.com/api/characters/1284', 'https://www.anapioficeandfire.com/api/characters/1289', 'https://www.anapioficeandfire.com/api/characters/1296', 'https://www.anapioficeandfire.com/api/characters/1299', 'https://www.anapioficeandfire.com/api/characters/1304', 'https://www.anapioficeandfire.com/api/characters/1317', 'https://www.anapioficeandfire.com/api/characters/1326', 'https://www.anapioficeandfire.com/api/characters/1333', 'https://www.anapioficeandfire.com/api/characters/1335', 'https://www.anapioficeandfire.com/api/characters/1336', 'https://www.anapioficeandfire.com/api/characters/1340', 'https://www.anapioficeandfire.com/api/characters/1346', 'https://www.anapioficeandfire.com/api/characters/1352', 'https://www.anapioficeandfire.com/api/characters/1355', 'https://www.anapioficeandfire.com/api/characters/1373', 'https://www.anapioficeandfire.com/api/characters/1383', 'https://www.anapioficeandfire.com/api/characters/1389', 'https://www.anapioficeandfire.com/api/characters/1396', 'https://www.anapioficeandfire.com/api/characters/1409', 'https://www.anapioficeandfire.com/api/characters/1410', 'https://www.anapioficeandfire.com/api/characters/1418', 'https://www.anapioficeandfire.com/api/characters/1430', 'https://www.anapioficeandfire.com/api/characters/1434', 'https://www.anapioficeandfire.com/api/characters/1442', 'https://www.anapioficeandfire.com/api/characters/1444', 'https://www.anapioficeandfire.com/api/characters/1453', 'https://www.anapioficeandfire.com/api/characters/1455', 'https://www.anapioficeandfire.com/api/characters/1456', 'https://www.anapioficeandfire.com/api/characters/1463', 'https://www.anapioficeandfire.com/api/characters/1466', 'https://www.anapioficeandfire.com/api/characters/1468', 'https://www.anapioficeandfire.com/api/characters/1470', 'https://www.anapioficeandfire.com/api/characters/1488', 'https://www.anapioficeandfire.com/api/characters/1499', 'https://www.anapioficeandfire.com/api/characters/1502', 'https://www.anapioficeandfire.com/api/characters/1515', 'https://www.anapioficeandfire.com/api/characters/1520', 'https://www.anapioficeandfire.com/api/characters/1523', 'https://www.anapioficeandfire.com/api/characters/1526', 'https://www.anapioficeandfire.com/api/characters/1529', 'https://www.anapioficeandfire.com/api/characters/1530', 'https://www.anapioficeandfire.com/api/characters/1531', 'https://www.anapioficeandfire.com/api/characters/1540', 'https://www.anapioficeandfire.com/api/characters/1547', 'https://www.anapioficeandfire.com/api/characters/1548', 'https://www.anapioficeandfire.com/api/characters/1549', 'https://www.anapioficeandfire.com/api/characters/1551', 'https://www.anapioficeandfire.com/api/characters/1559', 'https://www.anapioficeandfire.com/api/characters/1560', 'https://www.anapioficeandfire.com/api/characters/1565', 'https://www.anapioficeandfire.com/api/characters/1566', 'https://www.anapioficeandfire.com/api/characters/1568', 'https://www.anapioficeandfire.com/api/characters/1570', 'https://www.anapioficeandfire.com/api/characters/1573', 'https://www.anapioficeandfire.com/api/characters/1585', 'https://www.anapioficeandfire.com/api/characters/1596', 'https://www.anapioficeandfire.com/api/characters/1602', 'https://www.anapioficeandfire.com/api/characters/1620', 'https://www.anapioficeandfire.com/api/characters/16

In [27]:
books_df = pd.DataFrame(all_books.json())
books_df

,url,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,https://www.anapioficeandfire.com/api/books/1,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/books/2,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/books/3,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/books/4,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/books/5,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
5,https://www.anapioficeandfire.com/api/books/6,The Sworn Sword,978-0785126508,[George R. R. Martin],152,Marvel,United States,Hardcover,2008-06-18T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
6,https://www.anapioficeandfire.com/api/books/7,The Mystery Knight,978-0765360267,[George R. R. Martin],416,Tor Fantasy,United States,Paperback,2011-03-29T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
7,https://www.anapioficeandfire.com/api/books/8,A Dance with Dragons,978-0553801477,[George R. R. Martin],1040,Bantam Books,United States,Hardcover,2011-07-12T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
8,https://www.anapioficeandfire.com/api/books/9,The Princess and the Queen,978-0765332066,[George R. R. Martin],784,Tor Books,United States,Hardcover,2013-12-03T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[]
9,https://www.anapioficeandfire.com/api/books/10,The Rogue Prince,978-0345537263,[George R. R. Martin],832,Bantam Books,United States,Hardcover,2014-06-17T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[]

2. Получить информацию обо всех домах Вестероса (Houses) и сохранить в pd.DataFrame

In [28]:
all_houses = requests.get('https://www.anapioficeandfire.com/api/houses')
houses_df = pd.DataFrame(all_houses.json())
houses_df

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[]
1,https://www.anapioficeandfire.com/api/houses/2,House Allyrion of Godsgrace,Dorne,"Gyronny Gules and Sable, a hand couped Or",No Foe May Pass,[],[Godsgrace],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/285,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/3,House Amber,The North,,,[],[],,,,,,,[],[],[]
3,https://www.anapioficeandfire.com/api/houses/4,House Ambrose,The Reach,"Or, semy of ants gules",Never Resting,[],[],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/5,House Appleton of Appleton,The Reach,"Or, an apple tree eradicated proper fructed gu...",,[],[Appleton],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[]
5,https://www.anapioficeandfire.com/api/houses/6,House Arryn of Gulltown,The Vale,,,[],[Gulltown],,,https://www.anapioficeandfire.com/api/houses/7,,,,[],[],[]
6,https://www.anapioficeandfire.com/api/houses/7,House Arryn of the Eyrie,The Vale,A sky-blue falcon soaring against a white moon...,As High as Honor,"[King of Mountain and Vale (formerly), Lord of...","[The Eyrie (summer), Gates of the Moon (winter)]",https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/16,Coming of the Andals,https://www.anapioficeandfire.com/api/characte...,,[],[https://www.anapioficeandfire.com/api/houses/6],[https://www.anapioficeandfire.com/api/charact...
7,https://www.anapioficeandfire.com/api/houses/8,House Ashford of Ashford,The Reach,"Tenny, a sun in splendour beneath a chevron in...",Our Sun Shines Bright,[Lord of Ashford],[Ashford],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
8,https://www.anapioficeandfire.com/api/houses/9,House Ashwood,The North,,,[],[],,,https://www.anapioficeandfire.com/api/houses/34,,,,[],[],[]
9,https://www.anapioficeandfire.com/api/houses/10,House Baelish of Harrenhal,The Riverlands,"A field of silver mockingbirds, on a green fie...",,"[Lord Paramount of the Trident, Lord of Harren...",[Harrenhal],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/16,299 AC,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...

3. Получить информацию обо всех домах Вестероса, у которых есть девиз, и сохранить в pd.DataFrame

In [29]:
payload = {'hasTitles':'True'}
all_houses_has_titles = requests.get('https://www.anapioficeandfire.com/api/houses', params=payload)
houses_df = pd.DataFrame(all_houses_has_titles.json())
houses_df

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/7,House Arryn of the Eyrie,The Vale,A sky-blue falcon soaring against a white moon...,As High as Honor,"[King of Mountain and Vale (formerly), Lord of...","[The Eyrie (summer), Gates of the Moon (winter)]",https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/16,Coming of the Andals,https://www.anapioficeandfire.com/api/characte...,,[],[https://www.anapioficeandfire.com/api/houses/6],[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/houses/8,House Ashford of Ashford,The Reach,"Tenny, a sun in splendour beneath a chevron in...",Our Sun Shines Bright,[Lord of Ashford],[Ashford],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/10,House Baelish of Harrenhal,The Riverlands,"A field of silver mockingbirds, on a green fie...",,"[Lord Paramount of the Trident, Lord of Harren...",[Harrenhal],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/16,299 AC,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/houses/13,House Banefort of Banefort,The Westerlands,"A black hooded man, on a grey field, within a ...",,[Lord of Banefort],[Banefort],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/229,,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/14,House Bar Emmon of Sharp Point,The Crownlands,"Fretty argent and white, a swordfish embowed h...",,[Lord of Sharp Point],[Sharp Point],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/15,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
5,https://www.anapioficeandfire.com/api/houses/15,House Baratheon of Dragonstone,The Crownlands,"Or, a heart gules enflamed proper charged with...",,"[Lord of Dragonstone, King of Westeros]",[Dragonstone],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/16,284 AC,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
6,https://www.anapioficeandfire.com/api/houses/16,House Baratheon of King's Landing,The Crownlands,"A black crowned stag and a gold lion, combatan...",,[Lord of the Seven Kingdoms],[King's Landing],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,,283 AC,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
7,https://www.anapioficeandfire.com/api/houses/17,House Baratheon of Storm's End,The Stormlands,"A black crowned stag, on a gold field(Or, a st...",Ours is the Fury,"[Lord of Storm's End, Lord Paramount of the St...","[Storm's End, Dragonstone (House Baratheon of ...",https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/16,1 AC,https://www.anapioficeandfire.com/api/characte...,,[],[https://www.anapioficeandfire.com/api/houses/...,[https://www.anapioficeandfire.com/api/charact...
8,https://www.anapioficeandfire.com/api/houses/19,House Belmore of Strongsong,The Vale,"Six silver bells, 3, 2, 1, on a purple field(P...",,[Lord of Strongsong],[Strongsong],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/7,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
9,https://www.anapioficeandfire.com/api/houses/22,House Blackbar of Bandallon,The Reach,"Argent, a fess sable",,[Lord of Bandallon],[Bandallon],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...

In [30]:
houses_df['titles'].value_counts()

titles
[King of Mountain and Vale (formerly), Lord of the Eyrie, Defender of the Vale, Warden of the East]    1
[Lord of Ashford]                                                                                      1
[Lord Paramount of the Trident, Lord of Harrenhal]                                                     1
[Lord of Banefort]                                                                                     1
[Lord of Sharp Point]                                                                                  1
[Lord of Dragonstone, King of Westeros]                                                                1
[Lord of the Seven Kingdoms]                                                                           1
[Lord of Storm's End, Lord Paramount of the Stormlands]                                                1
[Lord of Strongsong]                                                                                   1
[Lord of Bandallon]                                                                                    1
Name: count, dtype: int64

Видим, что строк с пустым параметром titles нет.

**Работа с БД**

Установить библиотеку psycopg2 (pip install psycopg2-binary)

In [31]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.11/dist-packages (2.9.10)

Подключиться к БД - 1 балл

hint: используйте для подключения параметры Hostname, Database, User, Password, указанные на странице БД, и метод psycopg2.connect()

In [32]:
import psycopg2

In [33]:
host = 'hh-pgsql-public.ebi.ac.uk'
port = 5432
database = 'pfmegrnargs'
user = 'reader'
password = 'NWDMCE5xdipIjRrp'

try:
    # создаем подключение
    conn = psycopg2.connect(dbname=database, user=user, password=password, host=host)
except:
    print('Can`t establish connection to database')

Получите 10 строк из таблицы rnc_database - 2 балла

hint: используйте методы conn.cursor(), cursor.execute(), cursor.fetchall(). В SQL-запросе не забудьте использовать LIMIT 10

In [34]:
with conn.cursor() as cursor:
  query = "SELECT * FROM rnc_database LIMIT 10"
  cursor.execute(query)
  mc_10 = cursor.fetchall()

Второй вариант решения:

In [35]:
with conn.cursor() as cursor:
  query = "SELECT * FROM rnc_database"
  cursor.execute(query)
  mc_10_second_way = cursor.fetchmany(10)

In [36]:
mc_10 == mc_10_second_way

True

Сохраните полученные данные в pd.DataFrame - 1 балл

In [37]:
mc_10_df = pd.DataFrame(mc_10)
mc_10_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1,2017-05-01 00:00:00.000000,RNACEN,ENA,884,ENA,Y,,ENA,,412.0,10.0,900074.0,12086180,814855,provides a comprehensive record of the world's...,https://www.ebi.ac.uk/ena/browser/,"[{'upi': 'URS00002D0E0C', 'taxid': 10090}, {'u...",[{'title': 'The European Nucleotide Archive in...
1,5,2017-05-17 00:00:00.000000,RNACEN,VEGA,98,VEGA,N,,VEGA,PRJEB4568,NaN,NaN,NaN,0,0,is a repository for high-quality gene models p...,http://vega.sanger.ac.uk/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'The GENCODE v7 catalog of human lo...
2,26,2017-05-01 00:00:00.000000,RNACEN,GENCODE,450,GENCODE,N,,GENCODE,,889.0,32.0,205012.0,47677,2,produces high quality reference gene annotatio...,http://gencodegenes.org/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'GENCODE: the reference human genom...
3,55,2023-10-10 15:02:45.191606,RNACEN,MGNIFY,839,MGnify,Y,None,MGnify,None,151.0,27.0,3514.0,135924,1929,None,None,None,None
4,41,2017-05-01 00:00:00.000000,RNACEN,GENECARDS,867,MalaCards,Y,,GeneCards,,1298.0,16.0,347561.0,517673,1,"is a searchable, integrative database that pro...",https://www.genecards.org/,"[{'upi': 'URS0000EBFCE3', 'taxid': 9606}, {'up...",[{'title': 'The GeneCards Suite: From Gene Dat...
5,10,2017-05-01 00:00:00.000000,RNACEN,RDP,85,RDP,Y,,RDP,,1536.0,1337.0,1600.0,4779,2487,"provides quality-controlled, aligned and annot...",http://rdp.cme.msu.edu/,"[{'upi': 'URS0000434740', 'taxid': 338963}, {'...",[{'title': 'Ribosomal Database Project: data a...
6,20,2017-05-01 00:00:00.000000,RNACEN,LNCIPEDIA,883,LNCipedia,Y,,LNCipedia,,1534.0,200.0,152544.0,126876,1,is a comprehensive compendium of human long no...,http://www.lncipedia.org/,"[{'upi': 'URS000081175C', 'taxid': 9606}, {'up...",[{'title': 'An update on LNCipedia: a database...
7,43,2017-05-01 00:00:00.000000,RNACEN,SNORNADB,446,snoRNA Database,Y,,snoRNA Database,,50.0,45.0,74.0,680,10,is a curated collection of archaeal snoRNAs ma...,http://lowelab.ucsc.edu/snoRNAdb/,"[{'upi': 'URS0000600702', 'taxid': 340102}, {'...",[{'title': 'Homologs of small nucleolar RNAs i...
8,2,2017-05-01 00:00:00.000000,RNACEN,RFAM,886,RFAM,Y,,Rfam,,135.0,24.0,10656.0,1879595,14792,is a collection of non-coding RNA families rep...,http://rfam.org,"[{'upi': 'URS00000478B7', 'taxid': 9606}, {'up...",[{'title': 'Rfam 13.0: Shifting to a genome-ce...
9,46,2017-05-01 00:00:00.000000,RNACEN,PIRBASE,485,piRBase,Y,,piRBase,,28.0,15.0,40.0,200827,17,a database of various piRNA associated data to...,http://www.regulatoryrna.org/database/piRNA/,"[{'upi': 'URS0000061ED0', 'taxid': 9606}, {'up...",[{'title': 'piRBase: a comprehensive database ...

Получите значения столбцов display_name, num_sequences, num_organisms, , url для 10 строк из таблицы rnc_database - 2 балла

In [38]:
with conn.cursor() as cursor:
  query = "SELECT display_name, num_sequences, num_organisms, url FROM rnc_database LIMIT 10"
  cursor.execute(query)
  mc_10_some_cols = cursor.fetchall()

In [39]:
mc_10_some_cols_df = pd.DataFrame(mc_10_some_cols)
mc_10_some_cols_df

,0,1,2,3
0,ENA,12086180,814855,https://www.ebi.ac.uk/ena/browser/
1,VEGA,0,0,http://vega.sanger.ac.uk/
2,GENCODE,47677,2,http://gencodegenes.org/
3,MGnify,135924,1929,None
4,GeneCards,517673,1,https://www.genecards.org/
5,RDP,4779,2487,http://rdp.cme.msu.edu/
6,LNCipedia,126876,1,http://www.lncipedia.org/
7,snoRNA Database,680,10,http://lowelab.ucsc.edu/snoRNAdb/
8,Rfam,1879595,14792,http://rfam.org
9,piRBase,200827,17,http://www.regulatoryrna.org/database/piRNA/